### PR TITLE
Rename all instances of fisherman to watcher

### PR DESCRIPTION
**Pull request by 0xRampey**
## Objective

Rename all instances of fisherman to watcher

## Origin Document

https://github.com/pokt-network/pocket/issues/956

## Goals

- Make sure that Pocket networks specs are up to date with the new terminology of 'Watcher'

## Deliverable

- [x] Rename all instances of fisherman

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [x] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

---

**Creator**: @0xRampey 
**Co-Owners**: 

Also probably cue to merge in ADR https://github.com/pokt-network/pocket-network-protocol/pull/38 @dylanlott

### CODE REVIEW

**Comment by Olshansk** [comment]
@0xRampey Makes sure to update the metadata of PRs as well as issues. Going to update this one so PTAL.


Screenshot 2023-08-07 at 2 10 25 PM

**Review by Olshansk — CHANGES_REQUESTED** [review]
The changes  in this file LGTM but I want to understand the next steps w.r.t renaming it in the rest of the codebase.

Is there going to be a group of PRs changing the specs, the code, etc? Will it be one big PR or on a per module basis?

Please update the github description appropriately to answer the context above.

**Comment by 0xRampey** [comment]
@Olshansk I've updated the gameplan in the origin document and linked to it here. Lmk if that clears it up.

**Comment by RossiNYC** [comment]
@Olshansk we still need this ticket I think, right?

**Comment by Olshansk** [comment]
> @Olshansk we still need this ticket I think, right?

Yea, that's correct. And one for renaming `Servicer` to `Supplier` as well.

**Pull request closed without merging**
